### ISSUE TITLE
Написать руководство разработчика (Виндовс)

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#1]

**Comment by AmirkhanMullabaev** [comment]
Руководство разработчика для Windiws готово и находится в [вики](https://github.com/ESDP2015-4/student-crm/wiki/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-Windows)
