### ISSUE TITLE
добавить Paperclip для модели Student

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#10]
# Что сделать
Обеспечить с помощью Paperclip загрузку файла - картинки для аватара студента. А также его корректного отображения в нужных размерах (medium, thumb по умолчанию). Если аватар для студента не загружен, то должна отображаться какая-нибудь картинка типа "картинка еще не добавлен"

# Мотивация
Создать дополнительную идентификацию студента через аватар. 

# Как проверить
Допустим админ регистрирует нового студента и загружает его фото. И если переходит в кабинет студента, то вместе с другими данными, также отображается загруженное фото. А если админ еще заходит в страницу просмотра всех студентов, там также все загруженные картинки должны отобразиться корректно.

**Comment by rubymax** [comment]
Time planned 0.5hr
Time spent 0.5hr
