### ISSUE TITLE
Добавить необходимые поля в таблицу students

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#2]
# Что сделать

в таблицу должны быть добавлены поля: 
- Фамилия (lastname) - string
- Отчество (midlename) - string
- пол - string
- skype - string
- дата рождения - date
- паспортные данные - sting

с таблицы удалить поле - phone

# Мотивация Зачем это надо заказчику? 
* При необходимости искать, сортировать по значениям существующих полей. 

# Критерии оценки  
В базе данных должны появиться новые поля:
- Фамилия (lastname) - string
- Отчество (midlename) - string
- пол - string
- skype - string
- дата рождения - date
- паспортные данные - sting

и уже там не должно быть поля -  phone

**Comment by rubymax** [comment]
Time planned 0.5hr
Time spent 0.5hr
