### ISSUE TITLE
Перенастроить шаблонный текст письма Devise с ссылкой настроить пароль

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#22]
# Что сделать 

Изменить шаблонный текст письма с ссылкой отправляемой при регистрации таким образом: 

"Здравствуйте, уважаемый (ФИО студента)!
Вы получили это письмо, поскольку Вас зарегистрировали как студента в IT-Attractor. 
Для завершения регистрации вам необходимо перейти по ссылке и настроить новый пароль для своего кабинета. 
Если письмо ошибочно пришло к вам, то проигнорируйте. 
с уважением, Администрация IT-Attractor"

* Важно! При генерациии вьюшки Devise должно быть сгенерирована только вьюшка mailer, остальные вьюшки не должны генерироваться.
(rails generate devise:views -v mailer  сгенерирует вьюшку только для mailer)

# Мотивация 
Студенты должны получать письмо в нужной для админа форме

# Как проверить 
Допустим регистрируем нового студента, если успешно создан, то пришедшее письмо должен иметь выше описанный текст.

**Comment by rubymax** [comment]
Planned time 0.5h
Spent time 0.5h
