### ISSUE TITLE
Downgrade project

### ISSUE THREAD

**Issue by rubymax** [ESDP2015-4/student-crm#27]
Что сделать:
Вернуть проект в первоначальное положение. 

Зачем: 
В связи с коренным изменением моделей, принято решение начать проект сначала. 

Как проверить: 
Модели проекта должны соответствовать ТЗ проекта на картинке
https://drive.google.com/folderview?id=0Bx7KGqoLxvciVk1IenlYa21Qck0&usp=sharing_eid&ts=5644ab81

**Comment by shamkeev** [comment]
Time planed 5 mins
Time spent 5 mins

Reset master branch up to the commit, where bootstrap support was added
