### ISSUE TITLE
Создать seeds для модели User

### ISSUE THREAD

**Issue by rubymax** [ESDP2015-4/student-crm#30]
# Что сделать:
Создать seeds для модели User для всех необходимых ему полей: 
* Имя
* Фамилия
* Отчество
* пол
* Дата рождения
* Телефон1
* Телефон2
* skype
* паспортные данные

# Зачем: 
Для проверки работоспособности программы

# Как проверить: 
Допустим запустим команды:
- rake db:migrate:reset
- rake db:seed
Если в базе данных в таблицах появляются новые данные
То все правильно.

**Comment by AmirkhanMullabaev** [comment]
Time planned: 0.5h, time spent: 1h
