### ISSUE TITLE
Добавить ActiveAdmin 

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#4]
# Что сделать:
В итоге должны получить админ-панель со своей таблицей AdminUser. 
Добавить ресурс Student к ActiveAdmin, 
После закрытия #10 подключить Paperclip к ActiveAdmin

Настроить show(просмотр 1-го) страницу и new, edit формы ресурса со следующими полями
* Аватар (medium style в просмотре 1-го)
* Фамилия, 
* Имя, 
* Отчество 
* пол 
* Дата рождения 
* Список телефонов данного студента
* e-mail 
* skype 
* паспортные данные 
* курс 
* группа

настроит страницу просмотра всех студентов: 
*  Аватар в thumb style
*  Фамилия, 
*  Имя, 
*  Отчество 
*  курс 
*  группа

Должна быть пагинация
Добавить пользователя админа - seed.rb

# Мотивация, зачем
Заказчик должен получить CRUD для сущности студент

# Критерии оценки
Допустим  админу нужно добавить студента и открывает форму добавления, если успешно добавлен, то открывает для редактирования. После успешного редактирования, нужно перейти на страницу отображения одного, а потом всех студентов.

**Comment by rubymax** [comment]
Planned time 3hr
Spent time 5hr
