### ISSUE TITLE
Поиск решений по реализации учебных программ курсов

### ISSUE THREAD

**Issue by shamkeev** [ESDP2015-4/student-crm#45]
### Что сделать
Провести исследование по возможным вариантам решения проблемы с реализацией модуля учебных программ курсов. Рассмотреть вариант использования Google Drive API, а также редактор WYSIWYG
### Зачем
Чтобы иметь представление как можно решить данную задачу и найти наиболее подходящие под требования заказчика. После этого можно будет дальше двигаться в проектировании модуля

**Comment by altynbek1977** [comment]
Изучено пути интеграции Google Drive нашему проекту. https://drive.google.com/open?id=0B3xstB7JmIiGMDd2YlcwdC1lcWc
