### ISSUE TITLE
Создать CRU на модель группы

### ISSUE THREAD

**Issue by shamkeev** [ESDP2015-4/student-crm#49]
### Что сделать
Необходимо добавить функционал добавления и редактирования групп. На форме добавления/редактирования группы должны быть след. поля:
* Название группы - текстовое поле, обязательное поле
* Курс - выбор из коллекции активных курсов (не завершившиеся), обязательное поле

Должна быть страница со списком всех групп, отсортированные по дате добавления - последние добавленные выше. На этой же странице, в правом верхнем углу должны быть кнопка "Добавить группу". В этом списке на каждую группу должны быть след. поля:
* Название группы
* Название курса
Если нажать на название курса, то можно будет перейти на страницу просмотра информации о данном курсе. 
Если нажать на название группы, то можно будет перейти на страницу просмотра информации о данной группе.
Страница просмотра информации о группе должна содержать след. данные:
* Название группы
* Название курса - является также ссылкой на просмотр информации о курсе
* Кнопку "Редактировать" в правом верхнем углу

* > Список студентов данной группы (будет реализовано в будущем)

Добавлять и редактировать группу может пользователь с ролями администратор и полный доступ.

### Зачем
Чтобы в дальнейшем была возможность распределять студентов по группам

### Как проверить
Допустим администратор зашел в систему.
Если в навигации он нажмет на кнопку "Группы", 
То откроется страница со списком всех групп.

Если нажать на "Добавить группу", 
То откроется форма создания новой группы.

Допустим в системе есть 3 курса, один из которых закончился в прошлом месяце.
Если на странице создания новой группы нажать на выпадающий список с курсами,
То в нем можно будет увидеть только 2 активных курса.

Если администратор ввел название группы и выбрал курс,
То после нажатия на кнопку "Сохранить" откроется страница с просмотром данных о созданной группе.

Если администратор не ввел название группы или не выбрал курс, то после нажатия на кнопку "Сохранить", система выдаст ему сообщение о не заполненных полях формы.

Если на странице просмотра данных нажать на кнопку "Редактировать",
то откроется форма редактирования данной группы.

**Comment by AmirkhanMullabaev** [comment]
Поступило дополнительное требование от заказчика: при редактировании группы, курс которой уже закончился, можно отредактировать только название группы, поле для редактирования курса должно быть недоступным.

**Comment by AmirkhanMullabaev** [comment]
Time planned: 3h
Time spent: 8h
Очень много времени ушло на поиск решения для отображения в списке курсов при создании группы только активных курсов.
