### ISSUE TITLE
В странице просмотра всех групп напротив каждой группы добавить кнопку “Добавить студентов”

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#61]
# Что сделать 
В странице просмотра всех групп  к таблице отображения добавить кнопку для добавления студентов в группу. 

# зачем это надо 
Облегчить пользователям добавление студентов группу, сократить путь добавления. 

# Как проверить 
Допустим открываем страницу отображения всех групп, и если нажимаем на кнопку "Добавить студента", то открывается форма добавления студента к группе.

**Comment by AmirkhanMullabaev** [comment]
Выполнено, функционал добавления студентов работает.
