### ISSUE TITLE
Создать Модель "Учебный блок"

### ISSUE THREAD

**Issue by ramablack** [ESDP2015-4/student-crm#71]
# Что сделать
Создать модель "Учебный блок" и связать его с моделью "Период"  посредством один-ко-многим, то есть  Учебный блок имеет много периодов, а у Периода  может быть только один Учебный блок.

# Зачем?
Для того чтобы при просмотре Календарного плана можно выбирать режимы просмотра: Можно просматривать текущий Учебный блок, прошедший Учебный Блок, будущий Учебный блок, текущий и два будущих Учебных блока, текущий и все будущие Учебные блоки, и полностью все Учебные блоки сразу.

* Учебный блок - это объединение нескольких занятий и может включать в себя любое количество занятий.
 Как правило Учебный блок это 8 занятий и Как правило он  длится один календарный месяц, но может начаться в одном месяце и закончиться в другом месяце.

# Как проверить
Допустим при просмотре Календарного плана занятий Студенты, Преподаватели и Администраторы курсов увидят таблицу в которой колонки это дни недели, а строки это недели, каждая ячейка такой таблицы это конкретный день, который содержит номер дня месяца и отметку о занятии, о вебинаре, о контрольной или о каникулах.

**Comment by shamkeev** [comment]
Time planned: 15 mins
Time spent: 20 mins
