### ISSUE TITLE
Обзор файлов с гугл драйва показать с вложенностью в папках

### ISSUE THREAD

**Issue by altynbek1977** [ESDP2015-4/student-crm#79]
# Что сделать
Выводить список папок и файлов в таком же порядке иерархии с вложенностью как в самом гугл драйве.

# Зачем
Упростить обзор файлов и папок для пользователя

# Допустим
Если открыть страницу добавления раздатки, то при нажатии на иконку папки, должно раскрываться список файлов и папок находящихся внутри него.

**Comment by altiwbek** [comment]
```
#79
```
