### ISSUE TITLE
Создать модель телефонов с нужными полями

### ISSUE THREAD

**Issue by AmirkhanMullabaev** [ESDP2015-4/student-crm#9]
## Что сделать
Создать модель телефонов (phones) с полями:
- phonenumber - string
- default - boolean, по умолчанию - TRUE
- student_id 
- foreign_key

последние два поля должны быть автоматически созданы миграцией AddStudentToPhones

Взаимосвязь должна быть один ко многим - у одного студента может быть множество телефонов, одним конкретным номером телефона может пользоваться только один студент.

В модели студента должна быть связь :has_many, в модели телефонов - :belongs_to

## Мотивация
Таким образом можно будет одному пользователю хранить сколько угодно телефонов в отдельной таблице. 

## Как проверить
В базе данных в таблице телефонов должны быть все необходимые поля
- phonenumber - string
- default - boolean
- student_id 
- foreign_key

В моделях должны быть прописаны связи :has_many для модели студента, в модели телефонов - :belongs_to

У экземпляров класса должны быть соответствующие связям методы.

**Comment by rubymax** [comment]
Time planned 0.5hr
Spent time 0.5hr
